repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args:
          - "--py310-plus"

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --force-exclude --fix --exit-non-zero-on-fix
        language: system
        types_or: [python, pyi, jupyter]
        require_serial: true

      - id: ruff-format
        name: ruff-format
        entry: ruff format --force-exclude
        language: system
        stages: [pre-commit]
        types_or: [python, pyi, jupyter]
        require_serial: true