name: Continuous Integration

on:
  push:
  pull_request:

concurrency:
  # Cancel running job if another commit is pushed to the branch
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: python
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest tests

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install 3.10

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest tests --cov

      - name: Prepare ./coverage.xml
        # Ignore the configured fail-under to ensure we upload the coverage report. We
        # will trigger a failure for coverage drops in a later job
        run: coverage xml --fail-under 0

      - name: Upload All coverage to Codecov
        uses: codecov/codecov-action@v4
        if: ${{ env.GITHUB_REPOSITORY }} == 'bmcandr/az-blob-stacio'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false

      - name: Check for coverage drop
        # This will use the configured fail-under, causing this job to fail if the
        # coverage drops.
        run: coverage report
