name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    if: ${{ github.repository }} == "bmcandr/az-blob-stacio"
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish
